In [1]:
import skmob2
import pandas as pd
import polars as pl
from skmob2.core import TrajectoryDataFrame
import time

# Evaluate fast path for single biggest user

In [2]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=None, names=['datetime', 'lat', 'lon', 'uidabc'])
tdf = TrajectoryDataFrame(df)
tdf

In [3]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.61607 seconds

# Evaluate fast path for all users

In [ ]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=None, names=['datetime', 'lat', 'lon', 'uidabc'])
tdf = TrajectoryDataFrame(df)
tdf.head()

In [4]:
tdf

In [5]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 4.13138 seconds

In [17]:
time_start = time.perf_counter()
tdf.jump_lengths()
time_end = time.perf_counter()
print(f"Time taken: {time_end - time_start}")

Time taken: 5.028946614009328

In [ ]:
tdf["jump_lengths"]

In [ ]:
df = load_dataset("brightkite")

tdf = skmob2.TrajDataFrame(df, timestamp=True)

jump_lengths = tdf.jump_lengths()

coefs, points = skmob2.mobility_laws.fit_power_law(jump_lengths)

# plotting logic