In [1]:
import time

import fastmob
import pandas as pd
import polars as pl
from fastmob.core import TrajDataFrame
from fastmob.data import load_dataset

# Evaluate fast path for single user polars

In [17]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pl.read_csv(
    path,
    separator="\t",
    has_header=True,
    new_columns=["uid", "datetime", "lat", "lng", "location id"],
)
tdf = TrajDataFrame(df, sort=True)
tdf

In [12]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.45726 seconds

In [4]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.44825 seconds

# Evaluate fast path for single biggest user

In [2]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=0,  names=["uidabc", "datetime", "lat", "lng", "location id"],)
tdf = TrajDataFrame(df, sort=False)
tdf

In [3]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.68621 seconds

In [6]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=0,  names=["uid", "datetime", "lat", "lng", "location id"],)
tdf = TrajDataFrame(df, sort=True)
tdf

In [7]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.18879 seconds

In [5]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.10251 seconds

In [3]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.18253 seconds

In [3]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.61607 seconds

In [ ]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=0,  names=["uidabc", "datetime", "lat", "lng", "location id"],)
tdf = TrajDataFrame(df, sort=False)
tdf

In [3]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 1.62543 seconds

# Evaluate fast path for all users

In [11]:
path = "../../../tests/shared/data/loc-brightkite_totalCheckins.txt.gz"
df = pd.read_csv(path, sep='\t', header=0,  names=["uid", "datetime", "lat", "lng", "location id"],)
tdf = TrajDataFrame(df, sort=True)
tdf.head()

,uid,datetime,lat,lng,location id
2098,0,2009-05-25 20:56:10+00:00,37.774929,-122.419415,ee81ef22a22411ddb5e97f082c799f59
2097,0,2009-05-25 21:35:28+00:00,37.600747,-122.382376,248b82709e6c11ddbf68003048c0801e
2096,0,2009-05-25 21:37:44+00:00,37.600747,-122.382376,248b82709e6c11ddbf68003048c0801e
2095,0,2009-05-25 21:42:47+00:00,37.600747,-122.382376,248b82709e6c11ddbf68003048c0801e
2094,0,2009-05-25 22:13:23+00:00,37.615223,-122.389979,be2f1e669cc111dd9a50003048c0801e

In [12]:
tdf

In [13]:
times = []

for i in range(5):
    time_start = time.perf_counter()
    tdf.jump_lengths()
    time_end = time.perf_counter()
    times.append(time_end - time_start)

print(f"Mean Time taken: {sum(times) / len(times):.5f} seconds")

Mean Time taken: 0.21652 seconds

In [14]:
tdf.jump_lengths()

         uid                                       jump_lengths
0          0  [19.640494457447723, 0.0, 0.0, 1.7434335091684...
1          1  [6.505339409923645, 46.75443058363974, 53.9285...
2          2  [0.0, 0.0, 0.0, 0.0, 3.641014748771287, 0.0, 5...
3          3  [3861.275963494035, 4.061636923656222, 5.91633...
4          4  [15511.949011944975, 0.0, 15511.949011944975, ...
...      ...                                                ...
51401  58222                                                 []
51402  58224                                                 []
51403  58225                                                 []
51404  58226                                                 []
51405  58227                                                 []

[51406 rows x 2 columns]

In [17]:
time_start = time.perf_counter()
tdf.jump_lengths()
time_end = time.perf_counter()
print(f"Time taken: {time_end - time_start}")

Time taken: 5.028946614009328

In [ ]:
tdf["jump_lengths"]

In [ ]:
df = load_dataset("brightkite")

tdf = fastmob.TrajDataFrame(df, timestamp=True)

jump_lengths = tdf.jump_lengths()

coefs, points = fastmob.mobility_laws.fit_power_law(jump_lengths)

# plotting logic